# Generated by Django 5.1.2 on 2024-10-28 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, default='default_title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime this object was created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The datetime this object was last updated'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime this object was created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The datetime this object was last updated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime this object was created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Maximum 160 characters. Provide a concise summary.', max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords. Maximum 10 keywords.', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Maximum 60 characters. Should be unique and descriptive.', max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The datetime this object was last updated'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The datetime this object was created'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The datetime this object was last updated'),
        ),
    ]
