# Generated by Django 5.1.2 on 2024-10-30 21:05

import djangify_backend.apps.portfolio.models
import djangify_backend.apps.portfolio.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_technology_title_alter_project_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Automatically generated thumbnail",
                null=True,
                upload_to=djangify_backend.apps.portfolio.utils.upload_to_project_thumb,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                help_text="Main project image (min 800x600px, max 5MB)",
                upload_to=djangify_backend.apps.portfolio.utils.upload_to_project,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    djangify_backend.apps.portfolio.models.validate_project_image,
                ],
            ),
        ),
    ]
