# Generated by Django 5.1.2 on 2024-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_project_thumbnail_alter_project_featured_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={"verbose_name_plural": "Technologies"},
        ),
        migrations.RemoveField(
            model_name="technology",
            name="name",
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="icon",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("typescript", "TypeScript"),
                    ("react", "React"),
                    ("django", "Django"),
                    ("nextjs", "Next.js"),
                    ("tailwindcss", "Tailwind CSS"),
                    ("shadcn", "shadcn/ui"),
                    ("fastapi", "FastAPI"),
                ],
                help_text="Select the technology icon",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
