# Generated by Django 5.1.2 on 2024-10-31 19:00

import djangify_backend.apps.portfolio.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_alter_technology_options_remove_technology_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="technology",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="thumbnail",
        ),
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a JPG or PNG image (max 5MB)",
                null=True,
                upload_to=djangify_backend.apps.portfolio.models.project_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    djangify_backend.apps.portfolio.models.validate_project_image,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(to="portfolio.technology"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(default="Default Title", max_length=200),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="caption",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                default="default.jpg",
                upload_to=djangify_backend.apps.portfolio.models.project_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    djangify_backend.apps.portfolio.models.validate_project_image,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="technology",
            name="icon",
            field=models.CharField(max_length=50),
        ),
    ]
