# Generated by Django 5.1.2 on 2024-10-31 19:20

import djangify_backend.apps.portfolio.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_rename_title_technology_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=djangify_backend.apps.portfolio.models.portfolio_gallery_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    djangify_backend.apps.portfolio.models.validate_portfolio_image,
                ],
            ),
        ),
    ]
