# Generated by Django 5.1.2 on 2024-10-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_alter_projectimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                related_name="projects", to="portfolio.technology"
            ),
        ),
    ]
