# Generated by Django 5.1.2 on 2024-10-31 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_alter_project_technologies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={"ordering": ["name"], "verbose_name_plural": "Technologies"},
        ),
    ]
