# Generated by Django 5.1.2 on 2024-11-01 20:33

import djangify_backend.apps.portfolio.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0011_rename_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
            },
        ),
        migrations.AlterModelOptions(
            name="portfolioimage",
            options={
                "ordering": ["order"],
                "verbose_name": "Portfolio Image",
                "verbose_name_plural": "Portfolio Images",
            },
        ),
        migrations.RemoveField(
            model_name="portfolioimage",
            name="project",
        ),
        migrations.AddField(
            model_name="portfolioimage",
            name="portfolio",
            field=models.ForeignKey(
                help_text="Portfolio project this image belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="portfolio.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(help_text="Detailed description of the project"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="github_url",
            field=models.URLField(
                blank=True,
                help_text="GitHub repository URL",
                validators=[djangify_backend.apps.portfolio.models.validate_github_url],
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Display this project in featured sections"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Display order in the portfolio list"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="project_url",
            field=models.URLField(
                blank=True, help_text="Live project URL (if available)"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="short_description",
            field=models.CharField(
                help_text="Brief summary of the project", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly version of the title", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="technologies",
            field=models.ManyToManyField(
                help_text="Technologies used in this project",
                related_name="portfolios",
                to="portfolio.technology",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=models.CharField(
                default="Default Title",
                help_text="Title of the portfolio project",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioimage",
            name="caption",
            field=models.CharField(
                help_text="Description of the image", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="portfolioimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Additional project image (JPG or PNG)",
                null=True,
                upload_to=djangify_backend.apps.portfolio.models.portfolio_gallery_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    djangify_backend.apps.portfolio.models.validate_portfolio_image,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="portfolioimage",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Display order in the gallery"
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="icon",
            field=models.CharField(
                help_text="Icon identifier or URL for the technology",
                max_length=50,
                validators=[
                    djangify_backend.apps.portfolio.models.validate_technology_icon
                ],
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="name",
            field=models.CharField(
                help_text="Name of the technology (e.g., Python, React, Django)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="technology",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly version of the name", unique=True
            ),
        ),
    ]
